"""
    # notebook.ipynb
    |   from projectname.config import data_path
    |   import pandas as pd
    |   df = pd.read_csv(data_path)  # clean!
By using these config.py files,
we get clean code in exchange for an investment of time naming variables logically.
"""

#%% Import libraries
from pathlib import Path

#%% Define project's paths
# project_dir = Path(Path(__file__).parent.parent).resolve()
p = Path(__file__).absolute()
project_dir = p.parent.parent

data_raw_dir = project_dir / "data/raw"
data_processed_dir = project_dir / "data/processed"
data_cleaned_dir = project_dir / "data/cleaned"

docs_dir = project_dir / "docs"
mlflow_dir = project_dir / "mlflow"
models_dir = project_dir / "models"
notebooks_dir = project_dir / "notebooks"
pandas_profiling_dir = project_dir / "pandas_profiling"
pipelines_dir = project_dir / "pipelines"
reports_dir = project_dir / "reports"
sql_dir = project_dir / "sql"


#%% Some project stuff
shipdb_cols_to_drop = [
    "active",
    # 'air_draught',
    # 'ais_dim_a',
    # 'ais_dim_b',
    # 'ais_dim_c',
    # 'ais_dim_d',
    "area_no",
    "aux_engine_1",
    "aux_engine_1_b_year",
    "aux_engine_1_bhp",
    "aux_engine_1_engine_engine_count",
    "aux_engine_1_engine_engine_hp",
    "aux_engine_1_engine_engine_kw",
    "aux_engine_1_engine_engine_model",
    "aux_engine_1_engine_engine_rpm",
    "aux_engine_1_engine_propulsion",
    "aux_engine_1_engine_speed",
    "aux_engine_1_engine_total_hp",
    "aux_engine_1_engine_total_kw",
    "aux_engine_1_kw",
    "aux_engine_1_lic_builder",
    "aux_engine_1_no",
    "aux_engine_1_rpm",
    "aux_engine_1_shp",
    "aux_engine_2",
    "aux_engine_2_b_year",
    "aux_engine_2_bhp",
    "aux_engine_2_engine_engine_count",
    "aux_engine_2_engine_engine_hp",
    "aux_engine_2_engine_engine_kw",
    "aux_engine_2_engine_engine_model",
    "aux_engine_2_engine_engine_rpm",
    "aux_engine_2_engine_propulsion",
    "aux_engine_2_engine_speed",
    "aux_engine_2_engine_total_hp",
    "aux_engine_2_engine_total_kw",
    "aux_engine_2_kw",
    "aux_engine_2_lic_builder",
    "aux_engine_2_no",
    "aux_engine_2_rpm",
    "aux_engine_2_shp",
    "aux_engine_3",
    "aux_engine_3_b_year",
    "aux_engine_3_bhp",
    "aux_engine_3_kw",
    "aux_engine_3_lic_builder",
    "aux_engine_3_no",
    "aux_engine_3_rpm",
    "aux_engine_3_shp",
    "aux_engine_4",
    "aux_engine_4_b_year",
    "aux_engine_4_bhp",
    "aux_engine_4_kw",
    "aux_engine_4_no",
    "aux_engine_4_rpm",
    "aux_engine_4_shp",
    "aux_engine_5",
    "aux_engine_5_bhp",
    "aux_engine_5_kw",
    "aux_engine_6",
    "aux_engine_6_bhp",
    # 'bale',
    # 'ballast',
    # 'ballast_water',
    # 'beam_extreme',
    "beneficial_owner",
    "beneficial_owner_country",
    "beneficial_owner_eff_date",
    "beneficial_owner_region",
    # 'breadth_extreme',
    # 'breadth_moulded',
    # 'breadth_registered',
    "builder",
    "builder_country",
    "builder_region",
    # 'bulkheads',
    "callsign_original",
    # 'cargo_holds',
    "carrier",
    "cars",
    "category",
    # 'cgt',
    "charter_1_charter",
    "charter_1_charter.1",
    "charter_1_charter_beneficial_owner",
    "charter_1_charter_beneficial_owner_country",
    "charter_1_charter_beneficial_owner_region",
    "charter_1_charter_charterer",
    "charter_1_charter_charterer_country",
    "charter_1_charter_charterer_region",
    "charter_1_charter_company",
    "charter_1_charter_conclusion_date",
    "charter_1_charter_date",
    "charter_1_charter_date_conclusion_date",
    "charter_1_charter_date_conclusion_month",
    "charter_1_charter_date_conclusion_year",
    "charter_1_charter_date_duration_months",
    "charter_1_charter_date_duration_total_months",
    "charter_1_charter_date_duration_years",
    "charter_1_charter_date_event_date",
    "charter_1_charter_date_event_month",
    "charter_1_charter_date_event_quarter",
    "charter_1_charter_date_event_year",
    "charter_1_charter_date_record_created",
    "charter_1_charter_date_record_updated",
    "charter_1_charter_duration_months",
    "charter_1_charter_duration_total_months",
    "charter_1_charter_duration_years",
    "charter_1_charter_event_date",
    "charter_1_charter_flag",
    "charter_1_charter_record_created",
    "charter_1_charter_vessel_name",
    "class",
    "class_equipment_letters",
    "class_equipment_number",
    "class_notation",
    "class_rating",
    "classed_by",
    "classed_by_1",
    "classed_by_1_date_change",
    "classed_by_1_reason",
    "classed_by_1_status",
    "classed_by_2",
    "classed_by_2_date_change",
    "classed_by_2_reason",
    "classed_by_2_status",
    "commercial_manager",
    "commercial_manager_country",
    "commercial_manager_region",
    "completion_date",
    "contract_date",
    "contract_month",
    "contract_quarter",
    "contract_year",
    "country_place_of_build",
    "country_place_of_build2",
    # 'crude_capacity',
    "date_of_next_survey",
    "date_of_survey",
    # 'deadweight',
    # 'deck_teu',
    # 'decks_number',
    "delivery_date",
    "delivery_month",
    "delivery_quarter",
    "delivery_year",
    # 'depth',
    # 'depth_moulded',
    "depth_sorted",
    "derricks_cranes",
    # 'diesel_oil',
    # 'displacement',
    "dk_area",
    # 'draft',
    # 'draught',
    # 'draught_tropical',
    # 'draught_winter',
    # 'eng_total_bhp',
    # 'eng_total_kw',
    "engine_builder",
    # 'engine_power',
    "ex_name_1",
    "ex_name_10",
    "ex_name_11",
    "ex_name_12",
    "ex_name_13",
    "ex_name_14",
    "ex_name_15",
    "ex_name_16",
    "ex_name_17",
    "ex_name_18",
    "ex_name_19",
    "ex_name_1_eff_date",
    "ex_name_2",
    "ex_name_20",
    "ex_name_2_eff_date",
    "ex_name_3",
    "ex_name_3_eff_date",
    "ex_name_4",
    "ex_name_4_eff_date",
    "ex_name_5",
    "ex_name_6",
    "ex_name_7",
    "ex_name_8",
    "ex_name_9",
    # 'feu',
    "flag_country_code",
    "flag_normalized",
    "flag_standardized",
    # 'freeboard',
    # 'freeboard_summer',
    # 'freeboard_tropical',
    # 'freeboard_winter',
    # 'freshwater',
    # 'fuel',
    # 'fuel_oil',
    "fuel_type",
    # 'gas_oil',
    "gear",
    "gear_1_gear_gear_builder",
    "gear_1_gear_gear_builder_country",
    "gear_1_gear_gear_builder_id",
    "gear_1_gear_gear_builder_region",
    "gear_1_gear_gear_designer",
    "gear_1_gear_gear_designer_country",
    "gear_1_gear_gear_designer_id",
    "gear_1_gear_gear_designer_region",
    "gear_1_gear_gear_model",
    "gear_1_gear_gear_type",
    "gear_1_gear_ids",
    "gear_1_gear_parameters",
    "gear_2_gear_gear_model",
    "gear_2_gear_gear_type",
    "gear_2_gear_parameters",
    "general_1_general_company",
    "general_1_general_company1country",
    "general_1_general_company1name",
    "general_1_general_company1region",
    "general_1_general_company1type",
    "general_1_general_company2country",
    "general_1_general_company2name",
    "general_1_general_company2region",
    "general_1_general_company2type",
    "general_1_general_company3name",
    "general_1_general_company4name",
    "general_1_general_date_event_date",
    "general_1_general_date_event_month",
    "general_1_general_date_event_quarter",
    "general_1_general_date_event_year",
    "general_1_general_date_record_created",
    "general_1_general_date_record_updated",
    "general_1_general_details",
    "general_1_general_event_date",
    "general_1_general_event_month",
    "general_1_general_event_quarter",
    "general_1_general_event_type",
    "general_1_general_event_year",
    "general_1_general_flag",
    "general_1_general_price",
    "general_1_general_record_created",
    "general_1_general_record_updated",
    "general_1_general_vessel_name",
    "general_2_general_company",
    "general_2_general_date_event_date",
    "general_2_general_date_event_month",
    "general_2_general_date_event_quarter",
    "general_2_general_date_event_year",
    "general_2_general_date_record_created",
    "general_2_general_date_record_updated",
    "generator",
    "generator_company",
    "generator_description",
    "generator_make",
    "grain",
    # 'gross_tonnage',
    "group_owner",
    "group_owner_country",
    "group_owner_region",
    "grt",
    "hatchways",
    # 'hold_teu',
    "hull",
    "hull_material",
    # 'hull_type',
    "ice_class",
    # 'imo',
    "inert_gas_system",
    "inmarsat_b",
    "inmarsat_c",
    "inmarsat_fleet",
    "inmarsat_mini_m",
    "inmarsat_sim_cards",
    "ism_manager_address",
    "ism_manager_email",
    "ism_manager_fax",
    "ism_manager_imo",
    "ism_manager_location",
    "ism_manager_name",
    "ism_manager_phone",
    "ism_manager_telex",
    "ism_manager_website",
    "keel_laying_date",
    "keel_to_mast",
    "kind",
    "lane_meters",
    "launch_date",
    # 'length_bp',
    # 'length_overall',
    # 'length_registered',
    "lifting_equipment",
    # 'light_displacement_tonnes',
    "liquid_cap",
    # 'lube_oil',
    "main_engine",
    "main_engine_1_engine_engine_builder",
    "main_engine_1_engine_engine_builder_id",
    "main_engine_1_engine_engine_count",
    "main_engine_1_engine_engine_designer_id",
    "main_engine_1_engine_engine_hp",
    "main_engine_1_engine_engine_kw",
    "main_engine_1_engine_engine_make",
    "main_engine_1_engine_engine_model",
    "main_engine_1_engine_engine_rpm",
    "main_engine_1_engine_ids",
    "main_engine_1_engine_propulsion",
    "main_engine_1_engine_series",
    "main_engine_1_engine_speed",
    "main_engine_1_engine_total_hp",
    "main_engine_1_engine_total_kw",
    "main_engine_2_engine_engine_count",
    "main_engine_2_engine_engine_hp",
    "main_engine_2_engine_engine_kw",
    "main_engine_2_engine_engine_model",
    "main_engine_2_engine_engine_rpm",
    "main_engine_2_engine_propulsion",
    "main_engine_2_engine_speed",
    "main_engine_2_engine_total_hp",
    "main_engine_2_engine_total_kw",
    "main_engine_b_year",
    "main_engine_bhp",
    "main_engine_builder",
    # 'main_engine_kw',
    "main_engine_lic_builder",
    "main_engine_model",
    "main_engine_no",
    # 'main_engine_power',
    # 'main_engine_rpm',
    "main_engine_shp",
    "main_engine_type",
    "man_agent_address",
    "man_agent_e_mail",
    "man_agent_mob_phone",
    "man_agent_nation",
    "man_agent_post_no",
    "man_agent_telefax",
    "man_agent_telephone",
    "manager_address",
    "manager_email",
    "manager_fax",
    "manager_imo",
    "manager_location",
    "manager_name",
    "manager_phone",
    "manager_telex",
    "manager_website",
    # 'max_draught',
    # 'max_speed',
    # 'mcr_fuel_consumption',
    # 'mcr_speed',
    "mmsi",
    "multi_level_status_of_ship.0",
    "multi_level_status_of_ship.1",
    "multi_level_status_of_ship_date",
    # 'my_vessel_type.0',
    "my_vessel_type.1",
    # 'net_tonnage',
    "newbuilding_currency",
    "newbuilding_price",
    "operator_address",
    "operator_email",
    "operator_fax",
    "operator_imo",
    "operator_location",
    "operator_name",
    "operator_phone",
    "operator_telex",
    "operator_website",
    "other_class_society",
    "owner_address",
    "owner_email",
    "owner_fax",
    "owner_location",
    "owner_name",
    "owner_phone",
    "owner_telex",
    "owner_website",
    "p_i_insurer_1",
    "p_i_insurer_2",
    "p_i_insurer_date_1",
    "p_i_insurer_date_2",
    "panama_canal_net_tonnage",
    "passengers",
    "port_of_registry",
    "position",
    "position_time_seen",
    "propeller",
    "propeller_description",
    "propeller_make",
    "propelling_type",
    "reason_for_the_status",
    "reefer_feu",
    # 'reefer_pts',
    # 'reefer_teu',
    "register",
    "registered_owner_imo",
    "registry_notation",
    "rename_1_rename_company",
    "rename_1_rename_new_name",
    "rename_1_rename_old_name",
    "rename_1_rename_start_date",
    "safety_management_certificate_expiry_date",
    "safety_management_certificate_issued_date",
    "sale_1_sale_buyer",
    "sale_1_sale_buyer_country",
    "sale_1_sale_buyer_region",
    "sale_1_sale_company",
    "sale_1_sale_date",
    "sale_1_sale_date_event_date",
    "sale_1_sale_date_event_month",
    "sale_1_sale_date_event_quarter",
    "sale_1_sale_date_event_year",
    "sale_1_sale_date_record_created",
    "sale_1_sale_date_record_updated",
    "sale_1_sale_details",
    "sale_1_sale_event_date",
    "sale_1_sale_event_month",
    "sale_1_sale_event_quarter",
    "sale_1_sale_event_year",
    "sale_1_sale_flag",
    "sale_1_sale_ld_trate",
    "sale_1_sale_ldt",
    "sale_1_sale_price",
    "sale_1_sale_record_created",
    "sale_1_sale_record_updated",
    "sale_1_sale_sale_type",
    "sale_1_sale_seller",
    "sale_1_sale_seller_country",
    "sale_1_sale_seller_region",
    "sale_2_sale_company",
    "sale_2_sale_date_event_date",
    "sale_2_sale_date_event_month",
    "sale_2_sale_date_event_quarter",
    "sale_2_sale_date_event_year",
    "sale_2_sale_date_record_created",
    "sale_2_sale_date_record_updated",
    "scrapped",
    "scrubber_date",
    "scrubber_fitted",
    "scrubber_planned",
    "scrubber_type",
    # 'service_speed',
    "shipyard",
    "shipyard2",
    "size_class",
    "speed_consumpt",
    "status_date_normalized",
    "status_of_ship_standardized",
    "suez_canal_gross_tonnage",
    "suez_canal_net_tonnage",
    "summer_tpc",
    "survey_1",
    "survey_1_date",
    "survey_1_next_date",
    "survey_2",
    "survey_2_date",
    "survey_2_next_date",
    "tech_man",
    "tech_man_address",
    "tech_man_e_mail",
    "tech_man_internet",
    "tech_man_nation",
    "tech_man_post_no",
    "tech_man_telefax",
    "tech_man_telephone",
    # 'teu',
    "thruster",
    "thruster_description",
    "thruster_make",
    # 'total_aux_hp',
    # 'total_aux_kw',
    "total_loss",
    # 'total_main_hp',
    # 'total_main_kw',
    "trading_clean_or_dirty",
    "trailers",
    # 'trial_speed',
    "vessel_age",
    "vessel_name",
    "vessel_name_date",
    "vessel_name_eff_date",
    "vessel_name_original",
    "vessel_sub_type",
    "vessel_type",
    "vessel_type_new_building",
    "watertight_compartments",
    "yard_number",
    # 'year_of_built'
]

shipdb_cols_to_use = [
    # 'air_draught',
    "ais_dim_a",
    "ais_dim_b",
    "ais_dim_c",
    "ais_dim_d",
    # 'bale',
    "ballast",
    "ballast_water",
    "beam_extreme",
    "breadth_extreme",
    "breadth_moulded",
    "breadth_registered",
    "bulkheads",
    "cargo_holds",
    # 'cgt',
    # 'crude_capacity',
    "deadweight",
    "deck_teu",
    "decks_number",
    "depth",
    "depth_moulded",
    "diesel_oil",
    "displacement",
    # 'draft',
    "draught",
    "draught_tropical",
    "draught_winter",
    "eng_total_bhp",
    "eng_total_kw",
    "engine_power",
    # 'feu',
    "freeboard",
    "freeboard_summer",
    "freeboard_tropical",
    "freeboard_winter",
    "freshwater",
    "fuel",
    "fuel_oil",
    "gas_oil",
    "gross_tonnage",
    "hold_teu",
    "imo",
    "length_bp",
    "length_overall",
    "length_registered",
    "light_displacement_tonnes",
    "lube_oil",
    "main_engine_kw",
    "main_engine_power",
    "main_engine_rpm",
    "max_draught",
    "max_speed",
    # 'mcr_fuel_consumption',
    # 'mcr_speed',
    "my_vessel_type.0",
    "net_tonnage",
    "reefer_pts",
    "reefer_teu",
    "service_speed",
    "teu",
    # 'total_aux_hp',
    # 'total_aux_kw',
    # 'total_main_hp',
    # 'total_main_kw',
    "trial_speed",
    "year_of_built",
]
