name: ft-vutilize
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - cloudpickle==1.6.0
  - dataprep==0.2.15
  - fastapi==0.65.1
  - joblib==1.0.1
  - ipython=7.23.1
  - matplotlib==3.4.2
  - numpy==1.20.2
  - pandas==1.2.4
  - scikit-learn==0.23.2
  - scikit-optimize==0.8.1
  - scipy==1.5.3
  - seaborn==0.11.1
  - statsmodels==0.12.2
  - sweetviz==2.1.0
  - uvicorn==0.13.4
  - yellowbrick==1.3.post1
  - pip
  - pip:
      - mlflow
      - pandas-profiling==3.0.0
      - xgboost==1.4.1
